export const savedQuestions = [
  {
    id: 1,
    section: 1,
    text: "What is your preferred communication method?",
    subText: "",
    type: "radio",
    meta: {
      options: ["Email", "Phone", "Text", "Video Call"],
    },
    multipleSelection: false,
    required: false,
    image: null,
  },
  {
    id: 2,
    section: 1,
    text: "How would you rate the quality of our design resources?",
    meta: {
      scale: 5,
    },
    type: "rating",
    multipleSelection: false,
    required: false,
  },
  {
    id: 3,
    section: 1,
    text: "When was the last time you attended a design workshop or conference?",
    meta: {
      dateType: "date",
    },
    type: "datetime",
    multipleSelection: false,
    required: false,
  },
  {
    id: 4,
    section: 1,
    text: "Which type of design conference would you prefer?",
    meta: {
      options: ["UI/UX Design", "Graphic Design", "Web Design", "Product Design"],
    },
    type: "dropdown",
    multipleSelection: false,
    required: false,
  },
  {
    id: 5,
    section: 1,
    text: "Rate the presentation skills of the last workshop speaker you attended",
    meta: {
      min: 1,
      max: 5,
      leftLabel: "Poor",
      rightLabel: "Excellent",
    },
    type: "linearScale",
    multipleSelection: false,
    required: false,
  },
  {
    id: 6,
    section: 1,
    text: "What tools do you use for web development?",
    subText: "Please select one tool for each category.",
    type: "tickboxGrid",
    meta: {
      rows: ["Frontend", "Backend", "Database", "Version Control"],
      columns: ["Tool 1", "Tool 2", "Tool 3"],
    },
    multipleSelection: true,
    required: false,
    image: null,
  },
  {
    id: 7,
    section: 1,
    text: "What areas of design do you want to improve in?",
    subText: "",
    type: "text",
    meta: {
      options: [],
    },
    multipleSelection: false,
    required: false,
  },
  {
    id: 8,
    section: 1,
    text: "What are your future career goals?",
    subText: "",
    type: "text",
    meta: {
      options: [],
    },
    multipleSelection: false,
    required: true,
  },
  {
    id: 9,
    section: 1,
    text: "How satisfied are you with the current design process at your company?",
    subText: "",
    type: "rating",
    meta: {
      scale: 10,
    },
    multipleSelection: false,
    required: true,
  },
  {
    id: 10,
    section: 1,
    text: "Would you recommend working in your design team to others?",
    subText: "",
    type: "radio",
    meta: {
      options: ["Yes", "No"],
    },
    multipleSelection: false,
    required: true,
  },
];
