export const postEventSatisfactionQuestionData = [
    {
      id: 1,
      section: 1,
      text: "How would you rate the overall event experience?",
      subText: "",
      type: "rating",
      meta:{
        scale: 5,
        min: 1,
        max: 5,
        leftLabel: "Very Poor",
        rightLabel: "Excellent",
      },
      multipleSelection: false,
      required: true,
    },
    {
      id: 2,
      section: 1,
      text: "How satisfied were you with the event's organization?",
      subText: "",
      type: "rating",
      meta:{
        scale: 5,
        min: 1,
        max: 5,
        leftLabel: "Very Disorganized",
        rightLabel: "Very Organized",
      },
      multipleSelection: false,
      required: true,
    },
    {
      id: 3,
      section: 1,
      text: "How relevant was the content of the event to your needs?",
      subText: "",
      type: "rating",
      meta:{
        scale: 5,
      min: 1,
      max: 5,
      leftLabel: "Not Relevant",
      rightLabel: "Highly Relevant",
      },
      multipleSelection: false,
      required: true,
    },
    {
      id: 4,
      section: 1,
      text: "What did you think about the speakers and their presentations?",
      subText: "",
      type: "radio",
      meta:{
        options: ["Very Poor", "Poor", "Average", "Good", "Excellent"],
      },
      multipleSelection: false,
      required: true,
    },
    {
      id: 5,
      section: 1,
      text: "How likely are you to attend a similar event in the future?",
      subText: "",
      type: "radio",
      meta:{
      options: ["Not Likely", "Somewhat Likely", "Very Likely"],

      },
      multipleSelection: false,
      required: true,
    },
    {
      id: 6,
      section: 1,
      text: "What aspects of the event would you suggest for improvement?",
      subText: "",
      type: "text",
      meta:{
        options: [],
      },
      multipleSelection: false,
      required: false,
    },
    {
      id: 7,
      section: 1,
      text: "How did you find the networking opportunities during the event?",
      subText: "",
      type: "rating",
      meta:{
        scale: 5,
        min: 1,
        max: 5,
        leftLabel: "Very Poor",
        rightLabel: "Excellent",
      },
      multipleSelection: false,
      required: true,
    },
    {
      id: 8,
      section: 1,
      text: "Did you face any technical issues during the event?",
      subText: "",
      type: "radio",
      meta:{
        options: ["Yes", "No"],
      },
      multipleSelection: false,
      required: false,
    },
    {
      id: 9,
      section: 1,
      text: "Would you recommend this event to others?",
      subText: "",
      type: "radio",
      meta:{
        options: ["Yes", "No", "Maybe"],
      },
      multipleSelection: false,
      required: true,
    },
    {
      id: 10,
      section: 1,
      text: "Additional comments or feedback?",
      subText: "",
      type: "text",
      meta:{
        options: [],
      },
      multipleSelection: false,
      required: false,
    },
  ];
  